[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
utils = {path = "../utils"}
tokio = { version = "1.44.1", features = ["full"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = "0.3"
